machine_id: 1
node_id: 1

http_api:
  host: 0.0.0.0
  port: 8000
  timeout_secs: 120
  rate_limit:
    nr_requests: 100
    per_secs: 60

database:
  host: "localhost"
  port: 5432
  database_name: "bank"
  require_ssl: false
  max_connections: 10
  max_lifetime_secs: 1800
  idle_timeout_secs: 300
